services:
  - type: cron
    name: postino-scraper
    schedule: "0 0 1 * *"
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: |
      playwright install
      python scrape_postino.py
    envVars:
      - key: SUPABASE_URL
        fromEnv: SUPABASE_URL
      - key: SUPABASE_KEY
        fromEnv: SUPABASE_KEY
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: 0

